service: chromeless

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'prod'}
  region: ${opt:region}
  apiKeys:
    - chromeless-apikey-${self:provider.stage}
  ecr:
    images:
      chromeless:
        path: ./

functions:
  server:
    name: chromeless-server-${self:provider.stage}
    timeout: 900
    memorySize: 1024
    image:
      name: chromeless
    events:
      - http:
          path: /
          method: post
          private: true
