version: "3.5"

services:

  lambda:
    build:
      dockerfile: Dockerfile
      context: ../..
    command: ["sh", "entrypoint.sh"]
    entrypoint: ""
    working_dir: /work
    volumes:
      - /tmp:/data
      - .:/work


