version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6
  aws-ecr: circleci/aws-ecr@7.2.0
  serverless: circleci/serverless-framework@1.0.1

aliases:
  - &master_conditions
    filters:
      branches:
        only:
          - master
  - &not_master_conditions
    filters:
      branches:
        ignore:
          - master
  - &base_image
    machine:
      image: ubuntu-2004:202111-02
  - &fix_docker
    run:
      name: fix-docker
      command: |
        if [[ $CIRCLE_SHELL_ENV == *"localbuild"* ]]; then
          sudo chown $(whoami):$(whoami) /run/docker-temp.sock
        fi
  - &setup_latest_remote_docker
    setup_remote_docker:
      version: 19.03.13

jobs:
  pytest:
    environment:
      DOCKER_BUILDKIT: "1"
    parameters:
      chromeless-server-function-name:
        type: string
      apiurl:
        type: string
      apikey:
        type: string
    <<: *base_image
    steps:
      - checkout
      - aws-cli/setup
      - <<: *fix_docker
      - run:
          name: Configure env_file
          command: |
            CHROMELESS_SERVER_FUNCTION_NAME=<< parameters.chromeless-server-function-name >>
            API_URL="$<< parameters.apiurl >>"
            API_KEY="$<< parameters.apikey >>"

            # local
            # STAGE=dev
            # AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
            # AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)
            # AWS_REGION=$(aws configure get region)
            # AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
            # AWS_ECR_ACCOUNT_URL=$(aws sts get-caller-identity --query Account --output text).dkr.ecr.$(aws configure get region).amazonaws.com
            # AWS_DEFAULT_REGION=$(aws configure get region)
            # API_URL=$(aws cloudformation describe-stacks --stack-name chromeless-${STAGE} --query "Stacks[0].Outputs[?OutputKey=='ServiceEndpoint'].OutputValue" --output text)
            # API_KEY=$(aws apigateway get-api-keys --query "items[?name=='chromeless-apikey-${STAGE}'].value" --include-values --output text)

            cat \<<EOF > pytest/.env
            LOCAL_PYTHON_VERSION=3.7
            CHROMELESS_SERVER_FUNCTION_NAME=$CHROMELESS_SERVER_FUNCTION_NAME
            LOCAL_CHROMELESS_PYPI_VERSION=
            LOCAL_CHROMELESS_HOSTNAME=
            CACHEBUST=
            EOF

            [ "$CHROMELESS_SERVER_FUNCTION_NAME" != "local" ] && cat \<<EOF >> pytest/.env || true
            AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            AWS_REGION=$AWS_REGION
            AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            API_URL=$API_URL
            API_KEY=$API_KEY
            EOF
      - run:
          name: Test
          command: |
            CHROMELESS_SERVER_FUNCTION_NAME=<< parameters.chromeless-server-function-name >>
            DOCKER_COMPOSE_EXTRA_YMLS=$( [ "$CHROMELESS_SERVER_FUNCTION_NAME" = "local" ] && echo "  -f pypi/docker-compose.local.yml" || echo "")
            docker-compose -f pypi/docker-compose.yml $DOCKER_COMPOSE_EXTRA_YMLS up --build --force-recreate -d
            PYPI_RELEASE_VERSION=$(grep -Po '[0-9]+.[0-9]+.[0-9]+' chromeless/__version__.py)

            CHROMELESS_VERSIONS=('0.2.9' '0.3.0' '0.3.6' '0.4.7' '0.4.8' $PYPI_RELEASE_VERSION)
            [ "$CHROMELESS_SERVER_FUNCTION_NAME" == "local" ] && CHROMELESS_VERSIONS=("${CHROMELESS_VERSIONS[@]:5}") || true

            for i in "${!CHROMELESS_VERSIONS[@]}"; do
                sed -r "s/LOCAL_CHROMELESS_PYPI_VERSION=.*$/LOCAL_CHROMELESS_PYPI_VERSION=${CHROMELESS_VERSIONS[$i]}/g; s/LOCAL_CHROMELESS_HOSTNAME=.*$/LOCAL_CHROMELESS_HOSTNAME=chromeless$(date +%s)$RANDOM/g; s/CACHEBUST=.*$/CACHEBUST=$(date +%s)$RANDOM/g" -i pytest/.env
                cat pytest/.env | grep LOCAL_CHROMELESS_PYPI_VERSION
                set -a && source pytest/.env && set +a
                docker-compose -f pytest/docker-compose.yml -p p$i up --build --force-recreate -d
            done
            for i in "${!CHROMELESS_VERSIONS[@]}"; do
                code=$(docker wait p${i}_pytest_1)
                mkdir -p /tmp/TESTS/${CHROMELESS_VERSIONS[$i]}
                docker logs p${i}_pytest_1 |& tee /tmp/TESTS/${CHROMELESS_VERSIONS[$i]}/pytest.txt
                docker logs p${i}_chromeless_1 |& tee /tmp/TESTS/${CHROMELESS_VERSIONS[$i]}/chromeless.txt
                docker kill p${i}_chromeless_1
                echo p${i}_pytest_1 finished with $code
                if (( code > 0 )); then exit $code; fi
            done

      - store_artifacts:
          path: tmp/TESTS

  sls:
    parameters:
      stage:
        type: string
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup
      - <<: *fix_docker
      - <<: *setup_latest_remote_docker
      - run:
          name: Deploy
          command: |
            sls deploy --stage << parameters.stage >> --region ${AWS_REGION} --conceal | grep -v "execute-api"

  pypi:
    parameters:
      repository:
        type: string
      username:
        type: string
      password:
        type: string
    <<: *base_image
    steps:
      - checkout
      - <<: *fix_docker
      - run:
          name: Skip if already published
          command: |
            REPOSITORY=<< parameters.repository >>
            HOST=$( [ "$REPOSITORY" = "testpypi" ] && echo "test.pypi.org" || echo "pypi.org")
            PYPI_RELEASE_VERSION=$(grep -Po '[0-9]+.[0-9]+.[0-9]+' chromeless/__version__.py)
            STATUS_CODE=$(curl -s -o /dev/null -I -w "%{http_code}" "https://${HOST}/pypi/chromeless/${PYPI_RELEASE_VERSION}/json")
            [ "$STATUS_CODE" == "200" ] && circleci-agent step halt
      - run:
          name: Publish
          command: |
            # local
            # PYPI_USERNAME_DEV=$(aws ssm get-parameter --name PYPI_USERNAME_TEST --query 'Parameter.Value' --output text --profile default)
            # PYPI_PASSWORD_DEV=$(aws ssm get-parameter --name PYPI_PASSWORD_TEST --query 'Parameter.Value' --output text --profile default)
            # PYPI_USERNAME_PROD=$(aws ssm get-parameter --name PYPI_USERNAME_PROD --query 'Parameter.Value' --output text --profile default)
            # PYPI_PASSWORD_PROD=$(aws ssm get-parameter --name PYPI_PASSWORD_PROD --query 'Parameter.Value' --output text --profile default)

            PYPI_USERNAME=${<< parameters.username >>}
            PYPI_PASSWORD=${<< parameters.password >>}
            REPOSITORY=<< parameters.repository >>
            docker-compose -f pypi/docker-compose.yml build
            docker-compose -f pypi/docker-compose.yml run publisher twine upload --verbose -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} --repository ${REPOSITORY} dist/*

workflows:
  version: 2
  main:
    jobs:
      - pytest:
          name: "pytest-local"
          chromeless-server-function-name: "local"
          apiurl: API_URL_DEV # not used
          apikey: API_KEY_DEV # not used
          <<: *not_master_conditions
      - pypi:
          name: "pypi-dev"
          repository: "testpypi"
          username: PYPI_USERNAME_DEV
          password: PYPI_PASSWORD_DEV
          <<: *not_master_conditions
      - sls:
          name: "sls-dev"
          stage: "dev"
          <<: *not_master_conditions
      - pytest:
          name: "pytest-dev"
          chromeless-server-function-name: "chromeless-server-dev"
          apiurl: API_URL_DEV
          apikey: API_KEY_DEV
          requires:
            - pypi-dev
            - sls-dev
      - sls:
          name: "sls-prod"
          stage: "prod"
          <<: *master_conditions
      - pypi:
          name: "pypi-prod"
          repository: "pypi"
          username: PYPI_USERNAME_PROD
          password: PYPI_PASSWORD_PROD
          <<: *master_conditions
      - pytest:
          name: "pytest-prod"
          chromeless-server-function-name: "chromeless-server-prod"
          apiurl: API_URL_PROD
          apikey: API_KEY_PROD
          requires:
            - pypi-prod
            - sls-prod
